### PR TITLE
Add Office 2016 recipes

### PR DESCRIPTION
**Pull request by MScottBlake**

### CODE REVIEW

**Comment by sheagcraig** [comment]
Awesome-let me check this out.

**Comment by MScottBlake** [comment]
Turns out the %VERSION% isn't working properly. Looking to see what I need to do to fix it. Any ideas?

**Comment by sheagcraig** [comment]
Um, well, technically the version should probably be %version%. I haven't looked that closely yet-preparing python-jss/spruce releases today.

**Comment by MScottBlake** [comment]
Just pushed an update that should fix this and use the `%pathname%` variable within the `pkg_path` field for extra future proofing.

**Comment by sheagcraig** [comment]
I've updated these to pass the validator.

Big question, however. Our existing smart group criteria mean that anyone with Excel 2011 (in testing) will get offered this update. @homebysix and @MScottBlake what do you think of this?

I'm not super worried about it, but imagine this situation (which is our organization ATM):

User has Office 2011 installed (whole fleet does), and is in testing group. User sees sparkly new Excel and can't wait to see if Clippy has been added back in. User installs Excel 2016. Excel 2016 doesn't work because they don't have the enterprise license package.

Again, not super worried, because they still *have* 2011 available. And this could be overridden if it were a problem.

**Comment by MScottBlake** [comment]
This is totally outside of the realm of my knowledge without doing research, but maybe changing the smart group criteria on these to also see if excel is version like 15.*

I'm not sure how to make that future proof either.

**Comment by homebysix** [comment]
Yes, I'd recommend limiting this smart group to Macs that have `version like 15.*`. Individual orgs can override that if needed.

I think that means we need an Office2016SmartGroupTemplate.xml file, yes?

**Pull request merged**
