### PR TITLE
Added JetBrains products and NodeJS

### PR DESCRIPTION
**Pull request by chilcote**

### CODE REVIEW

**Comment by homebysix** [comment]
Thanks for the contrib!

Looks like this PR needs to wait until all your pkg recipes find their way into the AutoPkg organization. Have you requested that the admins fork your repo?

It also looks like the Docker recipe identifier and description need adjustment. (The requirement for the description not to be blank is new, so you're forgiven for not knowing about that.)

```
----------------------------------------
 Testing recipe: CLion/CLion.jss.recipe 
----------------------------------------
Test: Parent Recipe is in AutoPkg org. Result: False

------------------------------------------
 Testing recipe: NodeJS/NodeJS.jss.recipe 
------------------------------------------
OK

--------------------------------------------
 Testing recipe: PyCharm/PyCharm.jss.recipe 
--------------------------------------------
Test: Parent Recipe is in AutoPkg org. Result: False

----------------------------------------------
 Testing recipe: WebStorm/WebStorm.jss.recipe 
----------------------------------------------
Test: Parent Recipe is in AutoPkg org. Result: False

------------------------------------------
 Testing recipe: Docker/Docker.jss.recipe 
------------------------------------------
Test: Parent Recipe is in AutoPkg org. Result: False
Test: Recipe identifier follows convention. ('com.github.jss-recipes.jss.Docker') Result: False
Test: SELF_SERVICE_DESCRIPTION is not blank. Result: False
```

**Comment by chilcote** [comment]
Thanks.  Updated those pieces in the recipe. 

Yeah I have a request with autopkg. I think Tim might be on holiday though.  https://github.com/autopkg/autopkg/issues/298

**Comment by homebysix** [comment]
Have you considered calling the recipes DockerBeta.jss instead of Docker.jss? If the beta Sparkle feed is hard-coded, calling it DockerBeta would be more descriptive. It would also clear the way for a potential "non-beta" Docker recipe in the future.

**Comment by chilcote** [comment]
I figured I'd just update the feed info when it goes public, but I'm happy to change that if you think it's cleaner.

**Comment by homebysix** [comment]
Oh, I didn't realize it was *only* beta right now. In that case, naming it Docker.jss.recipe and updating the feed upon public release sounds like the right thing to do. 👍

**Comment by chilcote** [comment]
Yay, less work for me!

**Comment by chilcote** [comment]
autopkg recipes are live now https://github.com/autopkg/chilcote-recipes

**Comment by homebysix** [comment]
Looks good!

**Pull request merged**
