### PR TITLE
Repository changes - file formatting.

### PR DESCRIPTION
**Pull request by novaksam**
The novaksam Casper Suite recipe contains a postinstall script that’ll
repair the folder icon.

### CODE REVIEW

**Comment by sheagcraig** [comment]
Two PR's? One for Casper Suite and one for giant XML tabbing changes?

**Comment by novaksam** [comment]
@sheagcraig Done :)

**Comment by homebysix** [comment]
Leading tabs are well suited to xml and recipe files, but I think scripts and text files are [better](https://twitter.com/homebysix/status/558859775752953857) with leading spaces. So I'd recommend leaving these files as is:

- __MSOffice2016VersionChecker/MSOffice2016VersionChecker.py__
- __Office2011Update/Office2011UpdateVersioner.py__

And skipping the `<script>` contents in these files:

- __Office2011Update/Office2011UpdateExtensionAttribute.xml__
- __Oracle Java 8 JDK/Oracle Java 8 JDKExtensionAttribute.xml__

Otherwise looks good to me.

**Comment by sheagcraig** [comment]
Oh yeah-tabs in python whitespace... Oh _hell_ no.

**Comment by homebysix** [comment]
Sorry @novaksam, I didn't realize you had updated this PR. Looks good now, to me.

**Pull request merged**
