### PR TITLE
updated OS_REQUIREMENTS for macOS Sierra support, updated SELF_SERVICE_DESCRIPTION

### PR DESCRIPTION
**Pull request by mpanighetti**
Updated JSS recipes for coconutBattery, Compressor, Final Cut Pro, GarageBand, iBooks Author, iMovie, Keynote, Logic Pro X, MainStage, Microsoft Remote Desktop, Motion, Numbers, Pages, Parallels Desktop, and Xcode to reflect current OS_REQUIREMENTS from vendors. Updated SELF_SERVICE_DESCRIPTION entries to better reflect vendor-provided copy when available or appropriate.

### CODE REVIEW

**Comment by homebysix** [comment]
This PR is a little tricky because it includes AppStoreApp recipe overrides, designated by their parent recipe:

```
	<key>ParentRecipe</key>
	<string>com.github.nmcspadden.pkg.appstore</string>
```

AppStoreApp recipe overrides package up the local version of the app on the Mac running AutoPkg. If the proposed changes are merged, many of these recipes (for example Pages) will not work as expected unless administrators are running AutoPkg on macOS Sierra and intend to deploy the latest version.

I think for now, I'd like to hold off on changing the OS_REQUIREMENTS for any AppStoreApp override. The change is eventually going to happen, but I want to think for a while about the best way to communicate it to the community in advance.

The self service descriptions and other changes look good! 👍

**Comment by mpanighetti** [comment]
Sounds good. May want to at least add 10.12.x support where noted so the installs don't block on Sierra deployments.

**Comment by mpanighetti** [comment]
Updated to revert OS_REQUIREMENTS on Apple's App Store entries. Let me know if anything else needs to be adjusted.

**Comment by homebysix** [comment]
Perfect, thanks!

**Pull request merged**
