### PR TITLE
OS Requirement Updates for High Sierra

### PR DESCRIPTION
**Pull request by novaksam**
Adding 10.13 to the OS requirements list for most applications, and adding 10.12 for some that were previously missing it.

### CODE REVIEW

**Comment by homebysix** [comment]
@novaksam - Have you confirmed (by testing or in developer notes) that all these apps are 10.13 compatible?

On first glance, I see Bartender is included, although only Bartender 3 is [10.13-compatible](https://www.macbartender.com/support). Similarly, Pages and Numbers are "AppStoreApp" recipes so compatibility depends on which version is installed locally.

**Comment by novaksam** [comment]
@homebysix I'm not sure what the best approach would be for the appstore apps, but I just went through and verified, either by running, dev docs, and looking for (won't run on 10.13) that the apps run on High SIerra. I did have to go back and remove some previous OS's that are no longer compatible, but those were for apps that I don't use, so I didn't really keep track of them.

**Comment by homebysix** [comment]
Sounds good. Because the OS requirements are overrideable, and because they can be fixed easily with PRs if needed, I'm OK merging this.

Thank you!

**Comment by novaksam** [comment]
@homebysix Since this is still slightly on this topic, and I wanted to chat before considering PR'ing the changes in, I wrote a MinimumOSExtractor processor that reads in the plist from an *.app and creates a list of valid OS's based on the OS of the mac running the script (over-writable if your autopkg mac is running a lower OS version for some reason **cough** APFS **cough** ).

Here's an example for firefox
https://github.com/autopkg/novaksam-recipes/commit/c7b546e6f15440646f849621e754b10e7a5554b4

screen shot 2017-11-02 at 2 32 27 pm

screen shot 2017-11-02 at 2 32 43 pm


Or a more interesting smart group example, iMovie

screen shot 2017-11-02 at 2 38 17 pm

**Comment by homebysix** [comment]
Very cool!

**Pull request merged**
