### PR TITLE
OS requirements, EA changes and software additions PR

### PR DESCRIPTION
**Pull request by novaksam**
I've made the following additions:
* Adobe Reader
* Adobe Shockwave Player
* Audacity

I've made the following changes:
OS requirements + Smart groups
* Compressor
* Final Cut Pro
* GarageBand
* iMovie
* iPhoto
* Keynote
* Motion
* Numbers
* Oracle Java 8
* Pages
* Skype
* XCode

Extension attribute modifications:
* Oracle Java 8 JDK
* Suspicious Package

### CODE REVIEW

**Comment by sheagcraig** [comment]
Hey @novaksam This is great! Thanks for doing this.

I wonder if @homebysix might like to comment on the os version situation.

JSSImporter has an argument for `os_requirements` which sets the setting of that name on the package object (you would see it in Casper Admin when you look at a package's details).

The downside to using this, solely, is that it just blocks the package from getting installed during a policy install-package run, making it fail. Perhaps it is better to instead have it not even scoped to machines which can't run it, as you've done above.

That being said, it would require us to revise the style guide (that's not a bad thing), and I don't want to Lone Wolf decide that change is ready. Feel me?

**Comment by sheagcraig** [comment]
As for the other recipes, have you run them against the recipe validator? (I'm super swamped, so I'll do so prior to merging them, but just didn't want you to wonder what was taking so long).

**Comment by novaksam** [comment]
My additions of Audacity and Shockwave both pass the validator but the recipes where I used smart groups to exclude OS versions throw up that the GROUP_TEMPLATE isn't correct, and a couple (JDK 8, for example) I need to do a little revision because I'm detecting the version inside of the jss recipe, which I know is a no-no :)

And I feel ya, especially when it's a shared project like this :)

**Comment by sheagcraig** [comment]
Cool-so, we'll get there. Just might take a few.

**Comment by homebysix** [comment]
@sheagcraig Yeah, I'm ambivalent about using smart groups to scope to particular OS versions, even if it is for a noble purpose like making sure requirements are met.

Do you think there's any chance that JSSImporter could augment `SmartGroupTemplate.xml` on the fly with additional criteria based on the `os_requirements` key, thus obviating the need for separate individual template files? I know that's a long shot.

**Comment by sheagcraig** [comment]
@novaksam There's a lot of great stuff here; can you split off the PR's into two groups:
1. Things that need os-requirements decision-making to happen.
2. Straight up brand new recipes.

I'm merging like a fiend tonight, so I should be able to get the group 2 ones in pronto.

**Comment by novaksam** [comment]
I can attempt to do that, though I'm not sure how exactly I would.

Should I just drop all of the OS changed recipes, and set them up as a separate PR?

**Comment by sheagcraig** [comment]
Yeah-that would work. I think the easiest would be to copy out all of the new / changed files and create two new branches, one for the "new" ones and one for the ones that need the os requirements changes. Then, once you push those to your fork, you should be able to PR them each individually. You could also revert stuff out of this existing one, but that's more work!

**Comment by novaksam** [comment]
I'll be working on getting these changes synced back up and do a new PR :)

**Pull request closed without merging**
