### PR TITLE
Add recipe for 1Password

### PR DESCRIPTION
**Pull request by MScottBlake**

### CODE REVIEW

**Comment by homebysix** [comment]
Looks like this recipe is specific to 1Password 5. Is that intentional?

**Comment by MScottBlake** [comment]
It's just 5 by default. The pkg recipe it's based on is 4 by default, it's just overriding the value. It could easily be set back to 4 by changing `MAJOR_VERSION`.

I can always set it back to 4 in the recipe, but figured that moving forward, 5 would be a more-sane default.

**Comment by sheagcraig** [comment]
@homebysix Any thoughts?

@MScottBlake et al, I need to update JSSRecipeCreator so that recipes automatically pass the validator for this repo! I can hammer it out with my vim skillz, but still! Getting there! Getting there!

**Comment by MScottBlake** [comment]
@sheagcraig I didn't even think to check the validator as it was made by your own tool. This recipe passes validation now, my bad.

Regarding @homebysix's question: We really just need to ask ourselves if we want to require an override for version 4 or version 5. I went ahead and made it 5 by default since there's no backwards compatibility issues to worry about.

**Comment by homebysix** [comment]
I think 5 by default is fine. Just wanted to make sure that was intentional and not left in by accident.

**Pull request merged**
