### PR TITLE
Extension Attribute performance optimizations

### PR DESCRIPTION
**Pull request by novaksam**
Did some testing and found that checking for file existence before
running a defaults is a bit more efficient.

# Without file checking.
time ./temp.sh
2015-12-18 10:41:28.272 defaults[7589:30395]
The domain/default pair of
(/Library/Frameworks/CUDA.framework/Versions/Current/Resources/Info.plis
t, CFBundleShortVersionString) does not exist
2015-12-18 10:41:28.284 defaults[7590:30400]
The domain/default pair of
(/Library/Frameworks/CUDA.framework/Versions/Current/Resources/Info.plis
t, CFBundleVersion) does not exist
<result>Not Installed</result>

real	0m0.025s
user	0m0.012s
sys	0m0.010s

# With file checking
time ./temp2.sh
<result></result>

real	0m0.013s
user	0m0.001s
sys	0m0.001s

### CODE REVIEW

**Comment by homebysix** [comment]
@novaksam - Is changing the `CFBundleVersion` to `CFBundleShortVersionString` on __Sassafras K2 ClientExtensionAttribute.xml__ intentional?

**Comment by novaksam** [comment]
Yup, they both come out to the same thing.

```
defaults read /Library/KeyAccess/KeyAccess.app/Contents/Info.plist                           
{
    CFBundleDevelopmentRegion = English;
    CFBundleExecutable = KeyAccess;
    CFBundleGetInfoString = "7.3.0.7 (c)1990-2015 Sassafras Software Inc.";
    CFBundleIconFile = "KeyAccess.icns";
    CFBundleIdentifier = "com.sassafras.KeyAccess";
    CFBundleInfoDictionaryVersion = "6.0";
    CFBundleName = KeyAccess;
    CFBundlePackageType = APPL;
    CFBundleShortVersionString = "7.3.0.7";
    CFBundleSignature = KSka;
    CFBundleVersion = "7.3.0.7";
    LSBackgroundOnly = 1;
    NSBGOnly = 1;
}
```

**Comment by sheagcraig** [comment]
If we're really trying to eke out performance here, we should try grep or awk. I just did a very informal survey, and none of the Info.plists on my apps are binary, so it's worth a shot. I'm rubbish at regexes for following lines though...

**Comment by novaksam** [comment]
Well I did this for performance, and to get rid of the excessive console entries for software that's not present when my machines checked it.

**Pull request merged**
