### PR TITLE
Adding Ping ID

### PR DESCRIPTION
**Pull request by rderewianko**
```
rderewianko@rderewianko-r ~/g/jss-recipes> python validate_recipes.py ~/git/jss-recipes/PingID/PingID.jss.recipe 
-----------------------------------------------------------------------------
 Testing recipe: /Users/rderewianko/git/jss-recipes/PingID/PingID.jss.recipe 
-----------------------------------------------------------------------------
OK

```

Oh hey! I'm adding a new recipe.. Not sure why it's showing it a copy of biba's file.. but it should be net new?

### CODE REVIEW

**Comment by rderewianko** [comment]
```
rderewianko@rderewianko-r ~> 
plutil -lint ~/git/jss-recipes/PingID/PingID.jss.recipe 
/Users/rderewianko/git/jss-recipes/PingID/PingID.jss.recipe: OK
```

**Comment by homebysix** [comment]
Thanks, first timer! :-) 

Just to clarify — Biba no longer exists, and has been replaced/rebranded with PingID? Changing the identifier of an existing recipe will break recipes for anybody using it, so I want to make sure Biba is no longer a thing before merging.

**Comment by rderewianko** [comment]
Biba is dead. It's now Amazon chime.. I'm not sure why GitHub kept calling it The same file... Even when I created a new file...

**Comment by rderewianko** [comment]
Digging it seems perhaps i had totally overlooked the removal of biba from the main repo...

**Pull request merged**
