### PR TITLE
Oraclejava9 2017 10 13

### PR DESCRIPTION
**Pull request by shawnhonsberger**
Built and successfully tested. Built using this PR I made 10/11 as the
parent Recipe: https://github.com/autopkg/recipes/pull/222.

### CODE REVIEW

**Comment by homebysix** [comment]
Hi friend!

I can't find the parent recipe this refers to, with identifier `com.github.autopkg.pkg.OracleJava9`. Can you point me to that, and is it in the AutoPkg org?

Also, the icon will need to be 128x128, 300x300, or 512x512 pixels square. (Transparent padding is OK.)

**Comment by shawnhonsberger** [comment]
Hi! Perhaps I submitted a little early. The parent recipe is still a PR: https://github.com/autopkg/recipes/pull/222. I'll fix the icon, and maybe I should wait until it gets merged in the autopkg/recipes repo.

**Comment by shawnhonsberger** [comment]
Hi @homebysix! It is now merged. Thank you! https://github.com/autopkg/recipes/blob/master/OracleJava/OracleJava9.pkg.recipe

**Comment by homebysix** [comment]
Looks good now. Thank you!

**Comment by shawnhonsberger** [comment]
Thank you! :)

**Pull request merged**
