### PR TITLE
OS Requirement updates

### PR DESCRIPTION
**Pull request by novaksam**
I went through and set OS requirements for every App I could find that wouldn’t run on at least 10.8 (so anything that requires 10.9 or newer).

### CODE REVIEW

**Comment by sheagcraig** [comment]
This one is interesting @novaksam. While it does prevent users from getting an un-executable update pushed onto their machines, it results in the policy failing, rather than not being scoped.

This is something that I haven't fully reconciled-would it make more sense to use OS version EA's to scope to custom smart groups instead? Especially, consider what happens with "os_requirements" and a frequency of "ongoing".

**Comment by novaksam** [comment]
Well I did think about that, but my thinking would be to use custom smart group templates, which could be a hassle to maintain.

What if JSSImporter processed the OS_REQUIREMENTS and automatically inserted the OS version numbers into the smart group criteria once it's done enumerating the smart group template?

**Comment by sheagcraig** [comment]
Now we're talking.

Never manage that manually!

Well... Of course, _someone_ has to keep up with the requirements from the vendor and enter them _somewhere_ in the recipe. But I like this idea.

Putting it into place would probably require adding:
- An OS Version extension attribute to the JSS
- Adding a criteria to the smart group templates.

BUT, until JAMF adds some smarter comparison operators to the criteria, an os version requirement of 10.10.4, 10.10.5, for example, would require at least two extension attributes, and use of the dreaded (and broken) OR.

Any ideas of what this would look like as a smart group criteria? (Think about stuff that comes out mid-OS cycle and is only available on >= 10.10.4, e.g.

**Comment by novaksam** [comment]
Well the mid-life cycle versions can be added to packages via comma separation...

Right now I'm using the OR on some smart groups in my repo and I've found them to be reliable, at least for something as simple as separating operating system versions.

https://gist.github.com/novaksam/5402d880c4979736798f 

I'm thinking that JSSImporter could just parse the OS_REQUIREMENTS argument, delimit it by comma, strip off and '.x', and add each delimited field as additional criteria to the smart group (which would require the OR operator).

**Comment by novaksam** [comment]
A thought that occurred to me last night: what if the OS requirements argument was formatted like "10.10.x,10.9.4-5" and JSSImporter processed it like this:

10.10.x:
pkg requirement: 10.10.x
smart group: Operating System like: 10.10

10.9.4-5:
pkg requirement: 10.9.4, 10.9.5
smart group: Operating System like: 10.9.4
smart group: Operating System like: 10.9.5

**Comment by homebysix** [comment]
I don't see a problem with merging this in now, since the default behavior of these recipes is Self Service only. Admins like myself who employ overrides to set the frequency to Ongoing are going to be responsible for catching compatibility errors and working around them.

I also think the JSSImporter smart grouping idea above is a good one. Perhaps we can continue the discussion in a dedicated thread. → https://github.com/sheagcraig/JSSImporter/issues/65

**Comment by sheagcraig** [comment]
@homebysix Two questions: 
- Are you sure that the tabbing is correct? Didn't you just do a big plutil -lint run on all of these?
- Should we pull a sample of apps and ensure the OS requirements are correct?

**Comment by homebysix** [comment]
@sheagcraig, I don't plan to be too picky about tabbing in PRs, because I'm going to keep linting regularly (e.g. https://github.com/autopkg/jss-recipes/commit/d48b3fdcd1e20b21dff6d827019460307a66949e).

I'm trusting that @novaksam already looked up the requirements, and that people will complain if they're wrong.

I suppose the validator could dig into the AutoPkg cache and look for an app left over from each recipe run, then compare the os_requirements to what's in the app's Info.plist, but that sounds like a lot of work (and might not be 100% reliable).

**Comment by sheagcraig** [comment]
Presumably, if you have a package, you have an installable app. While it
would be a lot of extra processing, I wouldn't necessarily shy away from
unpacking the package, finding the app, and looking in the Info.plist for
version requirements.

Arguably, there could be an argument to JSSImporter so that we could only
go to that work if it was an app expected to not work with older OS
versions (i.e. anything Apple).

This would make the recipes a little more resilient too-recipe writers
wouldn't have to update them every OS update.

**Pull request merged**
