### PR TITLE
Update MySQLWorkBench.jss.recipe

### PR DESCRIPTION
**Pull request by mdoyle1**
Added Big Sur, Catalina and Mojave.

### CODE REVIEW

**Comment by homebysix** [comment]
I'm not personally using the OS_REQUIREMENTS in Jamf packages right now — can you confirm that both `11.x` and `10.16.x` are functionally equivalent for allowing packages to be installed on Big Sur? We now have [other JSS recipes](https://github.com/autopkg/jss-recipes/pull/229#discussion_r523466306) in this repo that use `10.16.x`.

**Comment by mdoyle1** [comment]
For Big Sur, 11.x works, 10.16.x doesn't work, I get "Computer doesn't meet the OS Requirements".  I've tested on Big Sur 11.0.1.

**Comment by homebysix** [comment]
Thank you.

**Comment by d33t5** [comment]
With the update to Jamf 10.26 it now reports Big Sur as `11`, prior versions will still need `10.16.x` due to this reporting change. I am currently testing 10.26 and can confirm that adding `11.x` to the `OS_REQUIREMENTS` works for recipes used with Jamf 10.26+

**Pull request merged**
