### PR TITLE
Fixing: MySQLWorkbench Adding: MacVim Adding: Spring Tool Suite Adding: Chicken

### PR DESCRIPTION
**Pull request by rderewianko**
JSS Importer was failing.

### CODE REVIEW

**Comment by rderewianko** [comment]
Adding MacVim to this aswell.
```
 python validate.py /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/MacVim/MacVim.jss.recipe
----------------------------------------------------------------------------------------------------------------------
 Testing recipe: /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/MacVim/MacVim.jss.recipe 
----------------------------------------------------------------------------------------------------------------------
OK
```

**Comment by rderewianko** [comment]
```
python validate.py /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/Spring\ Tool\ Suite/Spring\ Tool\ Suite.jss.recipe
--------------------------------------------------------------------------------------------------------------------------------------------
 Testing recipe: /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/Spring Tool Suite/Spring Tool Suite.jss.recipe 
--------------------------------------------------------------------------------------------------------------------------------------------

```OK

**Comment by rderewianko** [comment]
```
python validate.py /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/Chicken/Chicken.jss.recipe 
------------------------------------------------------------------------------------------------------------------------
 Testing recipe: /Users/pingadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.jss-recipes/Chicken/Chicken.jss.recipe 
------------------------------------------------------------------------------------------------------------------------
OK
```

**Comment by sheagcraig** [comment]
Awesome work-thanks for the recipes @rderewianko.

In the future, I think (at least for me) it's easier for me to test and merge these if new additions each get their own PR. But no sweat-they're in. Thanks!

**Comment by rderewianko** [comment]
For some reason github wouldn't let me do them as separate merge
requests..  Not too sure why but I would also have preferred separate.  :(

**Comment by sheagcraig** [comment]
Are you talking about the github app?

You need to create a branch for each app you want to write a recipe for.
Then check it out, add just those files, commit, and then do a PR from that
branch. You can only do one PR per branch.

Does that make sense?

**Comment by rderewianko** [comment]
Ahh that's what i did wrong! I'll make sure to do that with the next round

**Pull request merged**
