### PR TITLE
add jss-recipie for googlevoiceandvideo plugin

### PR DESCRIPTION
**Pull request by AllWorkAndNoPlay**
Adds jss-recipie for google voice and video plugin. The JSS extension attribute populates on update asset inventory

### CODE REVIEW

**Comment by homebysix** [comment]
Thanks for the contribution @AllWorkAndNoPlay! A couple of comments:

- As per style guide, the icon should be 128x128 or 300x300.

- I'm inclined to suggest using spaces in the product name, because that's what Google does:

    screen shot 2016-03-03 at 11 45 54 am

    If you make this change, make sure to adjust the names of the .png and .xml files to match.
- The default description is often overridden by people who use the recipe, but should still have proper spelling and grammar. Instead of:

    ```
    <string>Hangouts, Have voice and video conversations from your computer. This plugin is for firefox and safari. </string>
    ```

    I might suggest:

    ```
    <string>A plugin for Firefox and Safari that enables you to connect to Google Hangouts and have voice and video conversations from your computer.</string>
    ```

    (Or something similar.)

Otherwise this looks good and passes validation.

**Comment by AllWorkAndNoPlay** [comment]
I've made the recommended changes.

**Comment by homebysix** [comment]
The `NAME` needs to be updated to match the filename.

Here's a command you can run to check whether the recipe meets our standards:
```
python validate_recipes.py Google\ Voice\ And\ Video/*.jss.recipe
```

When I run that now, I get a few errors related to `NAME`:
```
--------------------------------------------------------------------------
 Testing recipe: Google Voice And Video/Google Voice And Video.jss.recipe 
--------------------------------------------------------------------------
Test: Recipe has correct prefix (NAME: 'GoogleVoiceAndVideo') Result: False
Test: Recipe is in a subfolder named (NAME: 'GoogleVoiceAndVideo'). Result: False
Test: All files have prefix of product (NAME: 'GoogleVoiceAndVideo'). Result: False
Test: GROUP_TEMPLATE is 'SmartGroupTemplate.xml'. Result: False
Test: WARNING: Recipe has extension attributes. Extension attributes meet style guidelines. Result: False
Test: Icon is a 128x128px PNG file. (Icon not found) Result: False
```

**Comment by homebysix** [comment]
I incorporated the changes into #55.

**Pull request closed without merging**
