### PR TITLE
adding latest omni product recipes

### PR DESCRIPTION
**Pull request by chilcote**
Adds 10.12 to the limitations as well.

### CODE REVIEW

**Comment by homebysix** [comment]
Thanks, Joe! I can't accept this PR in its current state because of one specific issue:

- The `com.github.jss-recipes.jss.OmniFocus` identifier is shared by both the original OmniFocus.jss.recipe file and the new OmniFocus2.jss.recipe file, which I think will cause some confusion. The same goes for the other three recipes: OmniGraffle6, OmniOutliner4, and OmniPlan3.

But I also have more of a philosophical question: Why wouldn't administrators simply override the `%NAME%` to select the major version of the Omni Group software they wish to deploy? They could do the same for `%OS_REQUIREMENTS%`, since the requirements vary by version.

I don't think we should seek to create recipes for every combination of product version — that's why the `com.github.autopkg.pkg.omnigroupproduct` recipe exists, after all.

**Comment by chilcote** [comment]
Sorry, I have no idea.  I just copied what I could from the munki recipes.  I'm game for whichever you prefer.  If you want me to update the PR I will, if you cancel it, I won't 👍

**Comment by homebysix** [comment]
I'll add to the description of the recipes in question to make it clear that administrators can override the `%NAME%` to get a more recent version of the apps.

**Comment by chilcote** [comment]
Thanks!  Today I learned about overrides!

**Pull request closed without merging**
